name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Farhaan-ali-v
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake.svg"
          add: "output/github-contribution-grid-snake.svg"
